### ISSUE TITLE
Where is the mask M of GNNML3 in the code?

### ISSUE THREAD

**Issue by peterwu4084** [balcilar/gnn-matlang#1]
In the paper, there is a mask M in the equation (5). But I didn't find it in the code of GNNML3.
Help pls. THX.

**Comment by balcilar** [comment]
Hello, Thanks for your interest on the paper and code.
M is defined in pre-processing step. You can find it in  libs/utils.py file SpectralDesign class.
If recfield=1 it means M=(A+I) , if recfield=0 it means M=A.
I generally used recfield=1. 
So you can change M in preprocessing step  in any given demo by giving diffent recfield value of SpectralDesign transform such that:
```
transform = SpectralDesign(nmax=30,recfield=1,dv=1,nfreq=10,adddegree=True,laplacien=False,addadj=True)
```

But please do not forget to remove processed folder in the dataset folder if you change the parmaters of transform. Because pytorch-geometric reads processed file (previously preprocessed dataset with old params) if it is available.
